version: '3.4'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/speedio_api
      - gem_cache:/usr/local/bundle/gems
    ports:
      - '3000:3000'
    depends_on: 
      - db

volumes:
  gem_cache:
  db_data: