default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  password: postgres
  username: postgres

development:
  <<: *default
  database: speedio_api_development

test:
  <<: *default
  database: speedio_api_test

production:
  <<: *default
  database: speedio_api_production
  username: api
  password: <%= ENV['API_DATABASE_PASSWORD'] %>
